package com.onemoresong.app;
import android.app.*;import android.content.*;import android.os.*;import androidx.annotation.Nullable;import androidx.core.app.NotificationCompat;import androidx.media.session.MediaSessionCompat;import androidx.media.session.PlaybackStateCompat;
public class MusicService extends Service{
 static final String CH="oms";MediaSessionCompat session;
 @Override public void onCreate(){super.onCreate();if(Build.VERSION.SDK_INT>=26)((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).createNotificationChannel(new NotificationChannel(CH,"ONE MORE SONG",NotificationManager.IMPORTANCE_LOW));session=new MediaSessionCompat(this,"ONE MORE SONG");session.setActive(true);session.setCallback(new MediaSessionCompat.Callback(){@Override public void onPlay(){run("playAudio && playAudio()") ;}@Override public void onPause(){run("pauseAudio && pauseAudio()") ;}@Override public void onSkipToNext(){run("nextTrack && nextTrack()") ;}@Override public void onSkipToPrevious(){run("previousTrack && previousTrack()") ;}});update(false);}
 void run(String js){if(MainActivity.web!=null)MainActivity.web.post(()->MainActivity.web.evaluateJavascript("(function(){try{"+js+"}catch(e){}})();",null));}
 void update(boolean playing){session.setPlaybackState(new PlaybackStateCompat.Builder().setActions(PlaybackStateCompat.ACTION_PLAY|PlaybackStateCompat.ACTION_PAUSE|PlaybackStateCompat.ACTION_SKIP_TO_NEXT|PlaybackStateCompat.ACTION_SKIP_TO_PREVIOUS).setState(playing?PlaybackStateCompat.STATE_PLAYING:PlaybackStateCompat.STATE_PAUSED,PlaybackStateCompat.PLAYBACK_POSITION_UNKNOWN,1).build());PendingIntent pi=PendingIntent.getActivity(this,0,new Intent(this,MainActivity.class),PendingIntent.FLAG_IMMUTABLE);NotificationCompat.Builder n=new NotificationCompat.Builder(this,CH).setSmallIcon(android.R.drawable.ic_media_play).setContentTitle("ONE MORE SONG").setContentText("Odtwarzacz muzyki").setContentIntent(pi).setOngoing(playing).setVisibility(NotificationCompat.VISIBILITY_PUBLIC).setStyle(new androidx.media.app.NotificationCompat.MediaStyle().setMediaSession(session.getSessionToken()).setShowActionsInCompactView(0));startForeground(1,n.build());}
 @Override public int onStartCommand(Intent i,int f,int id){return START_STICKY;}@Override public void onDestroy(){session.release();super.onDestroy();}@Nullable @Override public IBinder onBind(Intent i){return null;}
}
